### ISSUE TITLE
Compléter le diaporama.

### ISSUE THREAD

**Issue by romain-warnan** [romain-warnan/presentation-webpack#1]
Modifier le fichier docs/diaporama/slides

**Comment by renaud23** [comment]
petite remarque sur es5 et import/export : node prévoit un système de gestion de module issu de CommonJS ([http://wiki.commonjs.org/wiki/Modules/1.1.1]). Il est compatible es5 et ne concerne pas bien sûr les navigateurs, mais on croisera souvant des instructions requiere dans les fichiers de conf (donc avant babel) qui ont besoin d'une compatibilité es5.
