### ISSUE TITLE
problème sous firefox insee

### ISSUE THREAD

**Issue by renaud23** [romain-warnan/presentation-webpack#3]
L'application ne fonctionne pas avec webpack sur la version de firefox installée sur le poste de travail.

**Comment by renaud23** [comment]
J'ai changé les preset-es2016 pour babel-preset-env et tout semble rentré dans l'ordre.

**Comment by romain-warnan** [comment]
Magique, limite ça vaudrait le coup de mettre ça dans la démo !

(Sans rire)
